{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "количество свободной оперативной памяти:",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "__auto" },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "утилизация CPU для node-exporter (в процентах, 100-idle):",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 - avg(irate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[1m])) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(node_load1{job=\"node-exporter\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(node_load5{job=\"node-exporter\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(node_load15{job=\"node-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "количество места на файловой системе:",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_filesystem_avail_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}